import 'package:flutter/material.dart';
import 'package:amplify_flutter/amplify_flutter.dart';
import 'package:amplify_auth_cognito/amplify_auth_cognito.dart';
import 'package:amplify_storage_s3/amplify_storage_s3.dart';

// Auto-generated by the Amplify CLI
import 'amplifyconfiguration.dart'; 
import 'login_screen.dart';
import 'home_screen.dart'; // හෝ ඔයාගේ ප්‍රධාන Screen එකේ file එක import කරන්න
import 'alert_service.dart'; 

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  print("🔌 Connecting to AWS Amplify...");
  await _configureAmplify();

  // Alert Service එක පණගැන්වීම
  final alertService = AlertService();
  await alertService.init();
  alertService.startMonitoring(); 

  runApp(const MyApp());
}

Future<void> _configureAmplify() async {
  try {
    final authPlugin = AmplifyAuthCognito();
    final storagePlugin = AmplifyStorageS3();
    
    await Amplify.addPlugins([authPlugin, storagePlugin]);
    await Amplify.configure(amplifyconfig);
    print("✅ Connected to AWS!");
  } catch (e) {
    print("❌ Could not configure Amplify: $e");
  }
}

class MyApp extends StatefulWidget {
  const MyApp({super.key});

  @override
  State<MyApp> createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  bool _isLoggedIn = false;
  bool _isLoading = true;

  @override
  void initState() {
    super.initState();
    _checkAuthStatus();
  }

  // දැනටමත් Session එකක් තියෙනවාද කියා පරීක්ෂා කිරීම
  Future<void> _checkAuthStatus() async {
    try {
      final session = await Amplify.Auth.fetchAuthSession();
      setState(() {
        _isLoggedIn = session.isSignedIn;
        _isLoading = false;
      });
    } catch (e) {
      debugPrint("Auth status check error: $e");
      setState(() {
        _isLoggedIn = false;
        _isLoading = false;
      });
    }
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'ReflectOS',
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color(0xFF0A0B10),
        primaryColor: const Color(0xFFC4D300),
      ),
      // Loading අවසන් වන තෙක් SplashScreen එකක් හෝ Indicator එකක් පෙන්වයි
      home: _isLoading 
        ? const Scaffold(
            body: Center(
              child: CircularProgressIndicator(color: Color(0xFFC4D300)),
            ),
          )
        // දැනටමත් ලොග් වී ඇත්නම් HomeScreen එකටද, නැත්නම් LoginScreen එකටද යවයි
        : (_isLoggedIn ? const HomeScreen() : const LoginScreen()),
    );
  }
}